/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class AgregarCiudad extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCiudad
     */
    public AgregarCiudad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelNombreCiudad = new javax.swing.JLabel();
        jTextFieldNombreCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRutaCiudad = new javax.swing.JTextField();
        jButtonBuscarRutaCiudad = new javax.swing.JButton();
        jButtonGuardarCiudad = new javax.swing.JButton();
        jButtonAtrasAgregarCiudad = new javax.swing.JButton();
        jLabelCargarCiudad = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.setFocusPainted(false);
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jLabelNombreCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNombreCiudad.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabelNombreCiudad.setForeground(new java.awt.Color(0, 0, 153));
        jLabelNombreCiudad.setText("Nombre de la ciudad:");
        jLabelNombreCiudad.setOpaque(true);
        add(jLabelNombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 310, 40));

        jTextFieldNombreCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldNombreCiudad.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jTextFieldNombreCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldNombreCiudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jTextFieldNombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 670, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Ruta de la imagen:");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 310, 40));

        jTextFieldRutaCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldRutaCiudad.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jTextFieldRutaCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldRutaCiudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jTextFieldRutaCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 670, -1));

        jButtonBuscarRutaCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBuscarRutaCiudad.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jButtonBuscarRutaCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonBuscarRutaCiudad.setText("Buscar");
        jButtonBuscarRutaCiudad.setActionCommand("BuscarRuta");
        jButtonBuscarRutaCiudad.setFocusPainted(false);
        add(jButtonBuscarRutaCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 240, 40));

        jButtonGuardarCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonGuardarCiudad.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jButtonGuardarCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonGuardarCiudad.setText("Guardar");
        jButtonGuardarCiudad.setActionCommand("GuardarCiudad");
        jButtonGuardarCiudad.setFocusPainted(false);
        add(jButtonGuardarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 450, -1));

        jButtonAtrasAgregarCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAtrasAgregarCiudad.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jButtonAtrasAgregarCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAtrasAgregarCiudad.setText("Atras");
        jButtonAtrasAgregarCiudad.setActionCommand("AtrasAgregarCiudad");
        add(jButtonAtrasAgregarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 700, -1, -1));

        jLabelCargarCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AgregarCiudad.jpg"))); // NOI18N
        add(jLabelCargarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtrasAgregarCiudad;
    public javax.swing.JButton jButtonBuscarRutaCiudad;
    public javax.swing.JButton jButtonGuardarCiudad;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCargarCiudad;
    private javax.swing.JLabel jLabelNombreCiudad;
    public javax.swing.JTextField jTextFieldNombreCiudad;
    public javax.swing.JTextField jTextFieldRutaCiudad;
    // End of variables declaration//GEN-END:variables
}
