/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonAgregarCioudad = new javax.swing.JButton();
        jButtonEditarCiudad = new javax.swing.JButton();
        jButtonCargarCiudad = new javax.swing.JButton();
        jButtonAgregarHeroe = new javax.swing.JButton();
        jButtonAgregarVillano = new javax.swing.JButton();
        jButtonAgregarAntiheroe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.setFocusPainted(false);
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jButtonAgregarCioudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAgregarCioudad.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonAgregarCioudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAgregarCioudad.setText("Agregar ciudad");
        jButtonAgregarCioudad.setFocusPainted(false);
        add(jButtonAgregarCioudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 360, -1));

        jButtonEditarCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEditarCiudad.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonEditarCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonEditarCiudad.setText("Editar ciudad");
        jButtonEditarCiudad.setFocusPainted(false);
        jButtonEditarCiudad.setMaximumSize(new java.awt.Dimension(196, 34));
        jButtonEditarCiudad.setMinimumSize(new java.awt.Dimension(196, 34));
        add(jButtonEditarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 360, -1));

        jButtonCargarCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCargarCiudad.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonCargarCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCargarCiudad.setText("Cargar ciudad");
        add(jButtonCargarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 360, -1));

        jButtonAgregarHeroe.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAgregarHeroe.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonAgregarHeroe.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAgregarHeroe.setText("Agregar heroe");
        jButtonAgregarHeroe.setFocusPainted(false);
        add(jButtonAgregarHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 360, -1));

        jButtonAgregarVillano.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAgregarVillano.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonAgregarVillano.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAgregarVillano.setText("Agregar villano");
        jButtonAgregarVillano.setFocusPainted(false);
        add(jButtonAgregarVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 360, -1));

        jButtonAgregarAntiheroe.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAgregarAntiheroe.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonAgregarAntiheroe.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAgregarAntiheroe.setText("Agregar antiheroe");
        jButtonAgregarAntiheroe.setFocusPainted(false);
        add(jButtonAgregarAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 350, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Comenzar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 1050, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonAgregarAntiheroe;
    public javax.swing.JButton jButtonAgregarCioudad;
    public javax.swing.JButton jButtonAgregarHeroe;
    public javax.swing.JButton jButtonAgregarVillano;
    public javax.swing.JButton jButtonCargarCiudad;
    public javax.swing.JButton jButtonEditarCiudad;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
