/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class PreJuego extends javax.swing.JPanel {

    /**
     * Creates new form PreJuego
     */
    public PreJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonAtrasPreJuego = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ciudades = new javax.swing.JList<>();
        jLabelPreviewMapa = new javax.swing.JLabel();
        jButtonPreviewCiudad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPreviewPJ1 = new javax.swing.JList<>();
        jLabelPreviewPJ1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPreviewPJ2 = new javax.swing.JList<>();
        jLabelPreviewPJ2 = new javax.swing.JLabel();
        jButtonPreviewPJ1 = new javax.swing.JButton();
        jButtonPreviewPJ2 = new javax.swing.JButton();
        jButtonJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.setFocusPainted(false);
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jButtonAtrasPreJuego.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAtrasPreJuego.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jButtonAtrasPreJuego.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAtrasPreJuego.setText("Atras");
        jButtonAtrasPreJuego.setActionCommand("AtrasPreJuego");
        jButtonAtrasPreJuego.setFocusPainted(false);
        add(jButtonAtrasPreJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 700, -1, -1));

        Ciudades.setBackground(new java.awt.Color(0, 0, 0));
        Ciudades.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        Ciudades.setForeground(new java.awt.Color(0, 0, 204));
        Ciudades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BosqueViejo", "CampoPelea", "CiudadIndu", "EdificioAlto", "NaveFuturistica", "NevadoInospito", "ParqueDivertido", "PuenteLamento", "TechosJapon" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Ciudades.setToolTipText("");
        jScrollPane1.setViewportView(Ciudades);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 180));

        jLabelPreviewMapa.setOpaque(true);
        add(jLabelPreviewMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 460, 270));

        jButtonPreviewCiudad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPreviewCiudad.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonPreviewCiudad.setForeground(new java.awt.Color(204, 0, 0));
        jButtonPreviewCiudad.setText("Preview");
        jButtonPreviewCiudad.setActionCommand("PreviewMapaPreJuego");
        jButtonPreviewCiudad.setFocusPainted(false);
        add(jButtonPreviewCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 310, 30));

        jListPreviewPJ1.setBackground(new java.awt.Color(0, 0, 0));
        jListPreviewPJ1.setForeground(new java.awt.Color(0, 0, 255));
        jListPreviewPJ1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListPreviewPJ1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 120, 180));

        jLabelPreviewPJ1.setOpaque(true);
        add(jLabelPreviewPJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 220, 180));

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setForeground(new java.awt.Color(0, 0, 204));

        jListPreviewPJ2.setBackground(new java.awt.Color(0, 0, 0));
        jListPreviewPJ2.setForeground(new java.awt.Color(0, 0, 204));
        jListPreviewPJ2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListPreviewPJ2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 320, 120, 180));

        jLabelPreviewPJ2.setOpaque(true);
        add(jLabelPreviewPJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 320, 220, 180));

        jButtonPreviewPJ1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPreviewPJ1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonPreviewPJ1.setForeground(new java.awt.Color(204, 0, 0));
        jButtonPreviewPJ1.setText("Preview");
        jButtonPreviewPJ1.setActionCommand("PreviewPJ1");
        jButtonPreviewPJ1.setFocusPainted(false);
        add(jButtonPreviewPJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 240, 30));

        jButtonPreviewPJ2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPreviewPJ2.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonPreviewPJ2.setForeground(new java.awt.Color(204, 0, 0));
        jButtonPreviewPJ2.setText("Preview");
        jButtonPreviewPJ2.setActionCommand("PreviewPJ2");
        jButtonPreviewPJ2.setFocusPainted(false);
        add(jButtonPreviewPJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 240, 30));

        jButtonJugar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJugar.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonJugar.setText("Jugar");
        jButtonJugar.setActionCommand("Partida");
        jButtonJugar.setFocusPainted(false);
        add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 910, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PreJuego.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> Ciudades;
    public javax.swing.JButton jButtonAtrasPreJuego;
    public javax.swing.JButton jButtonJugar;
    public javax.swing.JButton jButtonPreviewCiudad;
    public javax.swing.JButton jButtonPreviewPJ1;
    public javax.swing.JButton jButtonPreviewPJ2;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelPreviewMapa;
    public javax.swing.JLabel jLabelPreviewPJ1;
    public javax.swing.JLabel jLabelPreviewPJ2;
    public javax.swing.JList<String> jListPreviewPJ1;
    public javax.swing.JList<String> jListPreviewPJ2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
