/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonJugar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelJugar = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonJugar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJugar.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonJugar.setText("Jugar");
        jButtonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonJugar.setFocusPainted(false);
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 250, 40));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.setFocusPainted(false);
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jLabelJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Principal.jpg"))); // NOI18N
        add(jLabelJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonJugar;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelJugar;
    // End of variables declaration//GEN-END:variables
}
